const fs = require('fs');
const path = require('path');

const header = "// ---------- WARN! DO NOT EDIT BY HAND. THIS FILE IS AUTOMATICALLY GENERATED BY firebase-orm. ---------- \n\n";

for(const entry of fs.readdirSync('./src')) {
    const p = path.parse(entry);
    if(p.ext !== ".ts") {
        continue;
    }
    if(p.name == "type-mapper") {
        continue;
    }

    const out = `${__dirname}/../firebase-orm-client/src/${entry}`;
    const content = fs.readFileSync(`./src/${entry}`, 'utf8');
    fs.writeFileSync(out, header+content)
    console.log(`copied to: ${out}`);
}