"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getCurrentDB = exports.use = exports.addDBToPool = exports.runTransaction = exports.getRepository = exports.Fetcher = exports.Repository = exports.TransactionManager = exports.FirebaseEntity = exports.UpdateDateColumn = exports.CreateDateColumn = exports.ManyToOne = exports.OneToOne = exports.OneToMany = exports.Column = exports.PrimaryColumn = void 0;
var Entity_1 = require("./Entity");
Object.defineProperty(exports, "PrimaryColumn", { enumerable: true, get: function () { return Entity_1.PrimaryColumn; } });
Object.defineProperty(exports, "Column", { enumerable: true, get: function () { return Entity_1.Column; } });
Object.defineProperty(exports, "OneToMany", { enumerable: true, get: function () { return Entity_1.OneToMany; } });
Object.defineProperty(exports, "OneToOne", { enumerable: true, get: function () { return Entity_1.OneToOne; } });
Object.defineProperty(exports, "ManyToOne", { enumerable: true, get: function () { return Entity_1.ManyToOne; } });
Object.defineProperty(exports, "CreateDateColumn", { enumerable: true, get: function () { return Entity_1.CreateDateColumn; } });
Object.defineProperty(exports, "UpdateDateColumn", { enumerable: true, get: function () { return Entity_1.UpdateDateColumn; } });
Object.defineProperty(exports, "FirebaseEntity", { enumerable: true, get: function () { return Entity_1.FirebaseEntity; } });
var Repository_1 = require("./Repository");
Object.defineProperty(exports, "TransactionManager", { enumerable: true, get: function () { return Repository_1.TransactionManager; } });
Object.defineProperty(exports, "Repository", { enumerable: true, get: function () { return Repository_1.Repository; } });
Object.defineProperty(exports, "Fetcher", { enumerable: true, get: function () { return Repository_1.Fetcher; } });
Object.defineProperty(exports, "getRepository", { enumerable: true, get: function () { return Repository_1.getRepository; } });
Object.defineProperty(exports, "runTransaction", { enumerable: true, get: function () { return Repository_1.runTransaction; } });
Object.defineProperty(exports, "addDBToPool", { enumerable: true, get: function () { return Repository_1.addDBToPool; } });
Object.defineProperty(exports, "use", { enumerable: true, get: function () { return Repository_1.use; } });
Object.defineProperty(exports, "getCurrentDB", { enumerable: true, get: function () { return Repository_1.getCurrentDB; } });
//# sourceMappingURL=index.js.map